title: Redis Enterprise Automation Framework
description: Documentation for the Redis Enterprise Automation Framework
markdown: kramdown
nav_enabled: true

remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true

# Enable copy code buttons
enable_copy_code_button: true

# CSS
sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - /tmp/jekyll-remote-theme-*/just-the-docs-HEAD/_sass

# Include these files/folders
include:
  - assets/css/index.scss
  - data

# Aux links for the upper right navigation
aux_links:
  "Redis Enterprise Automation on GitHub":
    - "//github.com/redislabs/Redis-Enterprise"

# Footer content
footer_content: "Redis Enterprise Automation Framework"

# Collections for docs
collections:
  docs:
    output: true